export enum Role {
    VIEW_USERS = 'VIEW_USERS',
    CREATE_USER = 'CREATE_USER',
    EDIT_USER = 'EDIT_USER',

    VIEW_GROUPS = 'VIEW_GROUPS',
    CREATE_GROUP = 'CREATE_GROUP',
    EDIT_GROUP = 'EDIT_GROUP',
    DELETE_GROUP = 'DELETE_GROUP',

    VIEW_PROVINCES = 'VIEW_PROVINCES',
    CREATE_PROVINCE = 'CREATE_PROVINCE',
    EDIT_PROVINCE = 'EDIT_PROVINCE',
    DELETE_PROVINCE = 'DELETE_PROVINCE',

    VIEW_DISTRICTS = 'VIEW_DISTRICTS',
    CREATE_DISTRICT = 'CREATE_DISTRICT',
    EDIT_DISTRICT = 'EDIT_DISTRICT',
    DELETE_DISTRICT = 'DELETE_DISTRICT',

    VIEW_COMMUNES = 'VIEW_COMMUNES',
    CREATE_COMMUNE = 'CREATE_COMMUNE',
    EDIT_COMMUNE = 'EDIT_COMMUNE',
    DELETE_COMMUNE = 'DELETE_COMMUNE',

    VIEW_MEETINGS = 'VIEW_MEETINGS',
    CREATE_MEETING = 'CREATE_MEETING',
    EDIT_MEETING = 'EDIT_MEETING',
    DELETE_MEETING = 'DELETE_MEETING',
    EXPORT_MEETINGS = 'EXPORT_MEETINGS',

    VIEW_MEETING_REPORTS = 'VIEW_MEETING_REPORTS',
    VIEW_DISTRICT_REPORTS = 'VIEW_DISTRICT_REPORTS',
    VIEW_TRAINER_REPORTS = 'VIEW_TRAINER_REPORTS',

    MANAGE_ROLES = 'MANAGE_ROLES',

    MANAGE_FORMS = 'MANAGE_FORMS'
}
